name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ ã“ã®ã‚¸ãƒ§ãƒ–ã¯${{ github.event_name }}ã‚¤ãƒ™ãƒ³ãƒˆã«ã‚ˆã£ã¦è‡ªå‹•çš„ã«ãƒˆãƒªã‚¬ãƒ¼ã•ã‚Œã¾ã—ãŸã€‚"
      - run: echo "ğŸ§ ã“ã®ã‚¸ãƒ§ãƒ–ã¯ç¾åœ¨ã€GitHubã«ã‚ˆã£ã¦ãƒ›ã‚¹ãƒˆã•ã‚Œã¦ã„ã‚‹${{ runner.os }}ã‚µãƒ¼ãƒãƒ¼ä¸Šã§å®Ÿè¡Œã•ã‚Œã¦ã„ã¾ã™ï¼"
      - run: echo "ğŸ” ã‚ãªãŸã®ãƒ–ãƒ©ãƒ³ãƒã®åå‰ã¯${{ github.ref }}ã§ã€ãƒªãƒã‚¸ãƒˆãƒªã¯${{ github.repository }}ã§ã™ã€‚"
      - name: ãƒã‚§ãƒƒã‚¯ã‚¢ã‚¦ãƒˆã—ã¦ã„ã¾ã™ã€‚
        uses: actions/checkout@v4
      - name: ãƒãƒƒã‚¯ã‚¨ãƒ³ãƒ‰ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªã«ç§»å‹•ã—ã‚³ãƒ³ãƒ†ãƒŠã‚’ç«‹ã¡ä¸Šã’ã‚‹
        run: |
          cd backend
          docker-compose up -d
      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate.linux-amd64 /usr/local/bin/migrate
      - name: Run migrations
        run: |
          docker ps
          migrate -path backend/db/migrations -database "mysql://root:root@tcp(db:3306)/chat_db?sslmode=disable" up
        # ãƒã‚¤ã‚°ãƒ¬ãƒ¼ã‚·ãƒ§ãƒ³ãƒ•ã‚¡ã‚¤ãƒ«ãŒã‚ã‚‹ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªã¨æ­£ã—ã„ãƒ‡ãƒ¼ã‚¿ãƒ™ãƒ¼ã‚¹æ¥ç¶šæƒ…å ±ã‚’æŒ‡å®šã—ã¦ãã ã•ã„ã€‚
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - run: echo "ğŸ This job's status is ${{ job.status }}."
